/-
Copyright (c) 2026 Justin Hart, Viridis LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Justin Hart, Aristotle (Harmonic)

Formalization of "Symplectic structure on the slack of an information-rate
bound" (Hart 2026; PSIT / Run-035). Formal-verification target for the
Nature Physics submission: the symplectic-conjugation theorem (Theorem 1)
and the no-solo-saturation corollary (Corollary 1).

Lean version: leanprover/lean4:v4.28.0
Mathlib pin:  8f9d9cff6bd728b17a24e163c9402775d9e6a365
-/

import Mathlib

/-!
# PSIT — Symplectic Structure on the Slack Manifold

This module formalizes the linear-algebraic core of the symplectic-conjugation
theorem for the five-component slack decomposition of an information-rate
(Landauer-type) bound `dI/dt ≤ P·D/(k_B T ln 2)`.

## Coordinate convention

The five non-negative slack components are indexed by `Fin 5`:

* `0` — `geom`  (geometric / sensor-design slack)
* `1` — `meas`  (measurement back-action slack)
* `2` — `rank`  (computational-rank slack)
* `3` — `mut`   (mutualistic-coupling slack)
* `4` — `decoh` (planetary-decoherence slack — the central element)

The canonical conjugate pairs are `(geom, meas) = (0,1)` and
`(rank, mut) = (2,3)`; `decoh = 4` is central. (This index ordering is the
action–angle ordering; it is a relabelling of the paper's listing order
`(geom, rank, meas, decoh, mut)` and changes no mathematical content.)

## Main results

* `omega_skew`                — ω is alternating (skew-symmetric); for a
                                 constant-coefficient 2-form this is
                                 equivalent to closedness `dω = 0`.
* `omega_block_nondegenerate` — ω restricted to the 4-dimensional
                                 action–angle block is non-degenerate
                                 (`det = 1`).
* `omega_radical_decoh`       — the radical of ω is exactly the `decoh`
                                 axis: `decoh` is the unique central element.
* `conjugate_pairs`           — ω realises precisely the pairings
                                 `(geom,meas)` and `(rank,mut)`, each at unit
                                 symplectic invariant, with no cross-pairing.
* `psit_uniqueness`           — **Theorem 1 (symplectic conjugation).** Every
                                 non-degenerate alternating form on the
                                 action–angle block is `GL`-congruent to ω;
                                 equivalently ω is unique up to `Sp(4)`.
* `ham_preserves_self`        — the Hamiltonian flow generated by a slack
                                 component preserves that component
                                 (`{εᵢ,εᵢ} = 0`).
* `ham_moves_conjugate`       — the Hamiltonian flow generated by `εᵢ` moves
                                 its symplectic conjugate at unit rate
                                 (`|{εᵢ,ε_conj}| = 1`).
* `no_solo_saturation`        — **Corollary 1.** No single-component
                                 Hamiltonian flow can hold a conjugate pair
                                 at joint saturation: the joint zero-set is
                                 not flow-invariant.

## Scope

The five-component orthogonal decomposition itself (companion result, TSDT)
is *taken as given*: this module formalizes only the symplectic structure
carried by those five components and its no-go corollary. ω is a closed
2-form with a one-dimensional radical (the `decoh` axis); its restriction to
the four-dimensional action–angle block is a genuine symplectic form. The
contact-geometric refinement on the `decoh` axis, and the two conjectures of
the paper (square-root scaling; Koopman gap), are deliberately out of scope.
-/

set_option linter.mathlibStandardSet false
set_option maxHeartbeats 400000
set_option maxRecDepth 4000
set_option relaxedAutoImplicit false
set_option autoImplicit false

open Matrix BigOperators
open scoped Matrix

noncomputable section

namespace PSIT

/-! ## §1 The canonical symplectic 2-form -/

/-- The canonical symplectic 2-form on the slack manifold, in the
    action–angle coordinates `(geom, meas, rank, mut, decoh)`. The 4×4
    action–angle block is the standard symplectic matrix; the `decoh` row
    and column vanish, marking `decoh` as the central element. -/
def omega : Matrix (Fin 5) (Fin 5) ℝ :=
  !![ 0,  1,  0,  0,  0;
     -1,  0,  0,  0,  0;
      0,  0,  0,  1,  0;
      0,  0, -1,  0,  0;
      0,  0,  0,  0,  0]

/-- ω restricted to the four-dimensional action–angle block
    `(geom, meas, rank, mut)`. -/
def omega4 : Matrix (Fin 4) (Fin 4) ℝ :=
  !![ 0,  1,  0,  0;
     -1,  0,  0,  0;
      0,  0,  0,  1;
      0,  0, -1,  0]

/-- Standard basis vector `eᵢ` of the slack coordinate space `Fin 5 → ℝ`. -/
def e (i : Fin 5) : Fin 5 → ℝ := Pi.single i 1

/-- The value of the symplectic 2-form on two tangent vectors:
    `ω(u, v) = uᵀ · ω · v`. -/
def omegaForm (u v : Fin 5 → ℝ) : ℝ := u ⬝ᵥ omega.mulVec v

/-- The symplectic-conjugate of a slack index: `geom ↔ meas`, `rank ↔ mut`,
    `decoh` self-conjugate (central). -/
def conj (i : Fin 5) : Fin 5 := ![1, 0, 3, 2, 4] i

/-- The Hamiltonian vector field of the `i`-th slack coordinate with respect
    to ω: the vector `X` satisfying `ω.mulVec X = eᵢ` on the action–angle
    block. Given explicitly. `decoh` is central, so its Hamiltonian field
    is `0`. -/
def hamVF (i : Fin 5) : Fin 5 → ℝ :=
  ![ ![ 0,  1,  0,  0,  0],   -- hamVF geom  =  e meas
     ![-1,  0,  0,  0,  0],   -- hamVF meas  = -e geom
     ![ 0,  0,  0,  1,  0],   -- hamVF rank  =  e mut
     ![ 0,  0, -1,  0,  0],   -- hamVF mut   = -e rank
     ![ 0,  0,  0,  0,  0] ]  -- hamVF decoh =  0  (central)
    i

/-- Total slack: the sum of the five non-negative components,
    `ε = ε_geom + ε_meas + ε_rank + ε_mut + ε_decoh`. -/
def slackTotal (x : Fin 5 → ℝ) : ℝ := ∑ i, x i

/-- The Hamiltonian flow of slack-coordinate `i` for time `t`. Because ω is
    constant-coefficient, the flow of the constant field `hamVF i` is
    affine. -/
def hamFlow (i : Fin 5) (t : ℝ) (p : Fin 5 → ℝ) : Fin 5 → ℝ :=
  p + t • hamVF i

/-! ## §2 Theorem 1 — the symplectic-conjugation theorem -/

/-
**ω is alternating.** For a constant-coefficient 2-form, skew-symmetry is
    equivalent to closedness `dω = 0`; hence ω is a closed 2-form.
-/
theorem omega_skew : omegaᵀ = -omega := by
  ext i j ; fin_cases i <;> fin_cases j <;> norm_num [ omega ] ;

/-
**Non-degeneracy of the action–angle block.** ω restricted to the
    four-dimensional action–angle block has determinant 1, hence is
    non-degenerate.
-/
theorem omega_block_nondegenerate : omega4.det = 1 := by
  norm_num [ omega4, Matrix.det_succ_row_zero ];
  simp +decide [ Fin.sum_univ_succ, Fin.succAbove ] at *

/-
**`decoh` is the central element.** The radical of ω — the directions
    paired trivially with everything — is exactly the `decoh` axis (index
    `4`). Equivalently, `decoh` is the unique slack component whose Poisson
    bracket vanishes against all five components.
-/
theorem omega_radical_decoh (v : Fin 5 → ℝ) :
    omega.mulVec v = 0 ↔ ∀ i : Fin 5, i ≠ 4 → v i = 0 := by
  simp_all +decide [ funext_iff, Fin.forall_fin_succ, Matrix.mulVec, dotProduct ];
  simp +decide [ Fin.sum_univ_five, omega ] ;
  tauto

/-
**Canonical conjugate pairs.** ω pairs `geom` with `meas` and `rank`
    with `mut`, each at unit symplectic invariant, with no cross-pairing
    between the two action–angle planes. These are the canonical
    action–angle conjugate pairs of Theorem 1.
-/
theorem conjugate_pairs :
    omegaForm (e 0) (e 1) = 1 ∧ omegaForm (e 2) (e 3) = 1 ∧
    omegaForm (e 0) (e 2) = 0 ∧ omegaForm (e 0) (e 3) = 0 ∧
    omegaForm (e 1) (e 2) = 0 ∧ omegaForm (e 1) (e 3) = 0 := by
  unfold omegaForm at *;
  simp +decide [ e, omega, Matrix.mulVec, dotProduct ] at *;
  simp +decide [ Fin.sum_univ_succ, Pi.single_apply ] at *

/-! ### Helpers for psit_uniqueness (linear Darboux theorem) -/

/-- Pfaffian of a 4×4 matrix. For skew-symmetric matrices, `det A = (pfaffian4 A)²`. -/
private def pfaffian4 (A : Matrix (Fin 4) (Fin 4) ℝ) : ℝ :=
  A 0 1 * A 2 3 - A 0 2 * A 1 3 + A 0 3 * A 1 2

/-
Skew-symmetry entry relation: `A j i = -A i j`.
-/
private lemma skew_entry {A : Matrix (Fin 4) (Fin 4) ℝ} (hskew : Aᵀ = -A)
    (i j : Fin 4) : A j i = -(A i j) := by
  convert congr_fun ( congr_fun hskew i ) j using 1

/-
For 4×4 skew-symmetric A, `det A = (pfaffian4 A)²`.
-/
private lemma det_eq_pfaffian_sq {A : Matrix (Fin 4) (Fin 4) ℝ} (hskew : Aᵀ = -A) :
    A.det = pfaffian4 A ^ 2 := by
  simp +decide only [det_succ_row_zero, Fin.sum_univ_four, pfaffian4];
  simp +decide [ Fin.sum_univ_succ, Matrix.submatrix ] at *;
  simp +decide [ ← Matrix.ext_iff, Fin.forall_fin_succ ] at *;
  simp +decide [ Fin.succAbove ] at *;
  grind +ring

/-
If `det A ≠ 0` and A is skew, then `pfaffian4 A ≠ 0`.
-/
private lemma pfaffian_ne_zero {A : Matrix (Fin 4) (Fin 4) ℝ} (hskew : Aᵀ = -A)
    (hnondeg : A.det ≠ 0) : pfaffian4 A ≠ 0 := by
  exact fun h => hnondeg <| by rw [ det_eq_pfaffian_sq hskew ] ; norm_num [ h ] ;

/-
Row 0 of a nondegenerate skew-symmetric 4×4 matrix has a nonzero
    off-diagonal entry.
-/
private lemma row0_nonzero {A : Matrix (Fin 4) (Fin 4) ℝ} (hskew : Aᵀ = -A)
    (hnondeg : A.det ≠ 0) : A 0 1 ≠ 0 ∨ A 0 2 ≠ 0 ∨ A 0 3 ≠ 0 := by
  contrapose! hnondeg;
  rw [ det_eq_pfaffian_sq hskew ];
  unfold pfaffian4; aesop;

/-- The explicit change-of-basis matrix for the case `A 0 1 ≠ 0`.
    Derived via symplectic Gram–Schmidt: normalize the (0,1)-entry,
    clear cross-terms by a shear, then normalize the (2,3)-entry. -/
private noncomputable def buildM (A : Matrix (Fin 4) (Fin 4) ℝ) : Matrix (Fin 4) (Fin 4) ℝ :=
  let a := A 0 1
  let pf := pfaffian4 A
  !![1,       0,       A 1 2 / a,   A 1 3 / pf;
     0,       1 / a,   -(A 0 2 / a), -(A 0 3 / pf);
     0,       0,       1,            0;
     0,       0,       0,            a / pf]

/-
`det(buildM A) ≠ 0` when `A 0 1 ≠ 0` and `pfaffian4 A ≠ 0`.
-/
private lemma buildM_det_ne_zero {A : Matrix (Fin 4) (Fin 4) ℝ}
    (h01 : A 0 1 ≠ 0) (hpf : pfaffian4 A ≠ 0) : (buildM A).det ≠ 0 := by
  unfold buildM;
  simp +decide [ Matrix.det_succ_row_zero, h01, hpf ];
  simp +decide [ Fin.sum_univ_succ, Fin.succAbove ];
  tauto

/-
`(buildM A)ᵀ * A * buildM A = omega4` when A is skew with `A 0 1 ≠ 0`.
-/
private lemma buildM_spec {A : Matrix (Fin 4) (Fin 4) ℝ}
    (hskew : Aᵀ = -A) (h01 : A 0 1 ≠ 0) (hpf : pfaffian4 A ≠ 0) :
    (buildM A)ᵀ * A * buildM A = omega4 := by
  unfold buildM omega4;
  simp +decide [ ← Matrix.ext_iff, Fin.forall_fin_succ ];
  simp +decide [ Matrix.mul_apply, Fin.sum_univ_succ ] at *;
  simp_all +decide [ div_eq_mul_inv, mul_assoc, mul_comm, mul_left_comm, Fin.forall_fin_succ, Matrix.mulVec, dotProduct ];
  have := congr_fun ( congr_fun hskew 0 ) 0; have := congr_fun ( congr_fun hskew 1 ) 0; have := congr_fun ( congr_fun hskew 2 ) 0; have := congr_fun ( congr_fun hskew 3 ) 0; have := congr_fun ( congr_fun hskew 1 ) 1; have := congr_fun ( congr_fun hskew 2 ) 1; have := congr_fun ( congr_fun hskew 3 ) 1; have := congr_fun ( congr_fun hskew 2 ) 2; have := congr_fun ( congr_fun hskew 3 ) 2; have := congr_fun ( congr_fun hskew 3 ) 3; norm_num at * ;
  unfold pfaffian4 at *;
  grind

/-- Permutation matrix swapping indices 1 and 2. -/
private def pswap12 : Matrix (Fin 4) (Fin 4) ℝ :=
  !![1, 0, 0, 0; 0, 0, 1, 0; 0, 1, 0, 0; 0, 0, 0, 1]

/-- Permutation matrix swapping indices 1 and 3. -/
private def pswap13 : Matrix (Fin 4) (Fin 4) ℝ :=
  !![1, 0, 0, 0; 0, 0, 0, 1; 0, 0, 1, 0; 0, 1, 0, 0]

/-
Skew-symmetry is preserved under matrix congruence.
-/
private lemma conj_skew {A P : Matrix (Fin 4) (Fin 4) ℝ} (hskew : Aᵀ = -A) :
    (Pᵀ * A * P)ᵀ = -(Pᵀ * A * P) := by
  simp +decide [ ← mul_assoc, hskew ]

/-
Determinant under congruence: `det(Pᵀ A P) = det(P)² · det(A)`.
-/
private lemma conj_det (A P : Matrix (Fin 4) (Fin 4) ℝ) :
    (Pᵀ * A * P).det = P.det ^ 2 * A.det := by
  norm_num [ sq, mul_assoc ];
  exact Or.inl <| mul_comm _ _

private lemma pswap12_det : pswap12.det ≠ 0 := by
  unfold pswap12;
  norm_num [ Fin.sum_univ_succ, Matrix.det_succ_row_zero ];
  simp +zetaDelta at *

private lemma pswap13_det : pswap13.det ≠ 0 := by
  rw [ show pswap13 = Matrix.of ![![1, 0, 0, 0], ![0, 0, 0, 1], ![0, 0, 1, 0], ![0, 1, 0, 0]] by rfl ] ; norm_num [ Matrix.det_succ_row_zero ];
  simp +decide [ Fin.sum_univ_succ, Fin.succAbove ] at *

private lemma pswap12_entry (A : Matrix (Fin 4) (Fin 4) ℝ) :
    (pswap12ᵀ * A * pswap12) 0 1 = A 0 2 := by
      simp +decide [ Matrix.mul_apply, pswap12 ];
      simp +decide [ Fin.sum_univ_succ, Matrix.vecHead, Matrix.vecTail ]

private lemma pswap13_entry (A : Matrix (Fin 4) (Fin 4) ℝ) :
    (pswap13ᵀ * A * pswap13) 0 1 = A 0 3 := by
      unfold pswap13; norm_num [ Matrix.mul_apply ] ;
      simp +decide [ Fin.sum_univ_succ, Matrix.vecHead, Matrix.vecTail ]

/-
Congruence by a product `P * N` decomposes into nested congruences.
-/
private lemma congruence_compose (A P N : Matrix (Fin 4) (Fin 4) ℝ) :
    (P * N)ᵀ * A * (P * N) = Nᵀ * (Pᵀ * A * P) * N := by
  simp +decide only [transpose_mul, Matrix.mul_assoc]

/-
**Theorem 1 (symplectic conjugation) — uniqueness clause.**
    Every non-degenerate alternating bilinear form on the four-dimensional
    action–angle block is `GL`-congruent to ω: there exists an invertible
    change of basis `M` carrying any such form `A` to the canonical
    `omega4`. Equivalently, the canonical symplectic 2-form is unique up to
    the action of `Sp(4)` (the residual `ℝ`-freedom being the overall
    scale). This is the linear Darboux normal-form theorem for the
    slack manifold.
-/
theorem psit_uniqueness (A : Matrix (Fin 4) (Fin 4) ℝ)
    (hskew : Aᵀ = -A) (hnondeg : A.det ≠ 0) :
    ∃ M : Matrix (Fin 4) (Fin 4) ℝ, M.det ≠ 0 ∧ Mᵀ * A * M = omega4 := by
  -- Case analysis on which entry of row 0 is nonzero, using row0_nonzero.
  by_cases h01 : A 0 1 ≠ 0;
  · exact ⟨ buildM A, buildM_det_ne_zero h01 ( pfaffian_ne_zero hskew hnondeg ), buildM_spec hskew h01 ( pfaffian_ne_zero hskew hnondeg ) ⟩;
  · by_cases h02 : A 0 2 ≠ 0;
    · -- Let $A' = pswap12^T * A * pswap12$. By conj_skew, $A'$ is skew. By conj_det and pswap12_det, $A'$ is nondegenerate. By pswap12_entry, $A' 0 1 = A 0 2 ≠ 0$.
      set A' : Matrix (Fin 4) (Fin 4) ℝ := pswap12ᵀ * A * pswap12
      have hA'_skew : A'ᵀ = -A' := conj_skew hskew
      have hA'_nondeg : A'.det ≠ 0 := by
        have := pswap12_det; aesop;
      have hA'_01 : A' 0 1 ≠ 0 := by
        convert h02 using 1;
        convert pswap12_entry A using 1;
      -- Apply buildM to A'. Let N = buildM A'. Then N^T * A' * N = omega4 by buildM_spec.
      obtain ⟨N, hN_det, hN_spec⟩ : ∃ N : Matrix (Fin 4) (Fin 4) ℝ, N.det ≠ 0 ∧ Nᵀ * A' * N = omega4 := by
        exact ⟨ buildM A', buildM_det_ne_zero hA'_01 ( pfaffian_ne_zero hA'_skew hA'_nondeg ), buildM_spec hA'_skew hA'_01 ( pfaffian_ne_zero hA'_skew hA'_nondeg ) ⟩;
      refine' ⟨ pswap12 * N, _, _ ⟩ <;> simp_all +decide [ Matrix.mul_assoc ];
      · grind +suggestions;
      · grind +qlia;
    · -- Case 3: A 0 3 ≠ 0. Conjugate A by pswap13 to get A' = pswap13^T * A * pswap13.
      set A' := pswap13ᵀ * A * pswap13
      have hA'_skew : A'ᵀ = -A' := by
        grind +suggestions
      have hA'_nondeg : A'.det ≠ 0 := by
        simp +zetaDelta at *;
        exact ⟨ ⟨ pswap13_det, hnondeg ⟩, pswap13_det ⟩
      have hA'_01 : A' 0 1 ≠ 0 := by
        have hA'_01 : A' 0 1 = A 0 3 := by
          convert pswap13_entry A using 1;
        have := row0_nonzero hskew hnondeg; aesop;
      -- Apply buildM to A'. Let N = buildM A'.
      obtain ⟨N, hN⟩ : ∃ N : Matrix (Fin 4) (Fin 4) ℝ, N.det ≠ 0 ∧ Nᵀ * A' * N = omega4 := by
        exact ⟨ buildM A', buildM_det_ne_zero hA'_01 ( pfaffian_ne_zero hA'_skew hA'_nondeg ), buildM_spec hA'_skew hA'_01 ( pfaffian_ne_zero hA'_skew hA'_nondeg ) ⟩;
      use pswap13 * N;
      simp_all +decide [ Matrix.mul_assoc ];
      simp +zetaDelta at *;
      exact ⟨ hA'_nondeg.1.1, by simpa only [ Matrix.mul_assoc ] using hN.2 ⟩

/-! ## §3 Corollary 1 — no-solo-saturation -/

/-
The Hamiltonian flow generated by slack-component `εᵢ` preserves `εᵢ`
    itself: `ω(Xᵢ, Xᵢ) = 0`, i.e. `{εᵢ, εᵢ} = 0`. A single component
    cannot be reduced by running its own Hamiltonian.
-/
theorem ham_preserves_self (i : Fin 5) :
    omegaForm (hamVF i) (hamVF i) = 0 := by
  fin_cases i <;> dsimp [omegaForm, hamVF, omega] ; simp +decide [ dotProduct, mulVec ];
  · norm_num [ Fin.sum_univ_succ ];
  · norm_num [ Matrix.mulVec, dotProduct ];
    norm_num [ Fin.sum_univ_succ ];
  · norm_num [ Fin.sum_univ_succ, Matrix.mulVec, dotProduct ];
  · norm_num [ dotProduct, Matrix.mulVec ];
    norm_num [ Fin.sum_univ_succ ];
  · norm_num [ Fin.sum_univ_succ ]

/-
The Hamiltonian flow generated by `εᵢ` moves its symplectic conjugate
    `ε_{conj i}` at unit rate: the Poisson bracket `{εᵢ, ε_{conj i}}` has
    modulus `1`. This is the unit symplectic invariant `ω(eᵢ, e_{conj i})`
    of Corollary 1.
-/
theorem ham_moves_conjugate (i : Fin 5) (hi : i ≠ 4) :
    |omegaForm (hamVF i) (hamVF (conj i))| = 1 := by
  fin_cases i <;> simp +decide [ *, omegaForm ] at hi ⊢;
  · erw [ abs_eq ] <;> norm_num [ Fin.sum_univ_succ, Matrix.mulVec, dotProduct ];
    simp +decide [ omega, hamVF, conj ] at *;
  · norm_num [ Fin.sum_univ_succ, Matrix.mulVec, dotProduct, hamVF, conj, omega ];
  · unfold conj hamVF; norm_num [ Fin.sum_univ_succ, dotProduct, Matrix.mulVec ] ;
    simp +decide [ omega ] at *;
  · unfold hamVF conj; norm_num [ Fin.sum_univ_succ, Matrix.mulVec, dotProduct ] ;
    simp +decide [ omega ] at *

/-
**Corollary 1 (no-solo-saturation).**
    No single-component Hamiltonian flow can hold a conjugate pair at joint
    saturation. If the conjugate component `ε_{conj i}` starts saturated
    (`= 0`), then under the Hamiltonian flow generated by `εᵢ` it leaves
    zero immediately: for every `t ≠ 0` it is nonzero. Hence the joint
    zero-set of a conjugate pair is not invariant under any
    single-component Hamiltonian flow — saturation requires co-optimisation
    along the symplectic 2-form.
-/
theorem no_solo_saturation (i : Fin 5) (hi : i ≠ 4)
    (p : Fin 5 → ℝ) (hp : p (conj i) = 0) :
    ∀ t : ℝ, t ≠ 0 → (hamFlow i t p) (conj i) ≠ 0 := by
  fin_cases i <;> simp_all +decide [ hamFlow, hamVF ];
  · simp_all +decide [ conj ];
  · simp_all +decide [ conj ];
  · simp +decide [ conj ];
  · exact fun t ht => by erw [ Matrix.cons_val_succ' ] ; aesop;

end PSIT